scalar DateTime

# Main, Settings

type Fields {
  id: String!
  slug: String!
  settings: Settings
  event: EventPage
  post: PostPage

  LandingPage: LandingPage
  TeamPage: TeamPage
  LegalPage: LegalPage
  ServicePage: ServicePage
}

type Settings {
  logo: String!
  heroImage: String!
  refundPolicy: String
  links: [NavigationLink!]!
  address: String
  email: String
  phone1: String
  phone2: String
  link: String
}

type NavigationLink {
  label: String!
  url: String!
  description: String
}

# Pages

type LandingPage {
  template: String
  aboutSection: AboutSection!
  postsSection: PostsSection!
  coreLearningZoneSection: CoreLearningZoneSection!
  eventsSection: EventsSection!
  services: [Service!]!
  productsSection: ProductsSection!
  testimonials: [Testimonial!]!
  title: String
  videos: [Video!]!
  contactUsSection: ContactUsSection!
}

type AboutSection {
  heading: String!
  text: String!
}

type PostsSection {
  heading: String!
  subheading: String!
}

type CoreLearningZoneSection {
  heading: String!
  subheading: String!
  extraText: String
}

type EventsSection {
  heading: String!
  subheading: String!
}

type ProductsSection {
  heading: String!
  subheading: String!
  products: [Product!]!
}

type Service {
  title: String!
  image: String!
  name: String!
  description: String!
}

type Product {
  description: String!
  image: String!
  title: String!
  subtitle: String
  link: String
}

type Testimonial {
  author: String!
  role: String!
  testimonial: String!
}

type Video {
  link: String!
  title: String!
  subtitle: String
}

type ContactUsSection {
  heading: String!
}

type TeamPage {
  template: String
  title: String!
  subtitle: String!
  members: [Member!]!
}

type Member {
  name: String!
  role: String!
  photo: String!
  bio: String!
  linkedin: String
  video: String
}

type LegalPage {
  template: String
  privacyPolicy: String
  termsAndConditions: String
}

type ServicePage {
  template: String
  explanation: Explanation!
  benefits: String!
  title: String!
  subtitle: String!
}

type Explanation {
  text: String!
  image: String!
}

# Events

type EventPage {
  id: String!
  collection: String!
  slug: String!
  title: String!
  subtitle: String!
  description: String!
  image: String!
  video: String
  date: DateTime!
  duration: Int!
  language: [Language!]!
  isOnline: Boolean!
  location: String
  tickets: [Ticket!]!
}

enum Language {
  EN
  ES
}

type Ticket {
  id: String!
  description: String!
  price: Int!
  endsOn: String!
}

# Posts

type PostPage {
  id: String!
  collection: String!
  slug: String!
  title: String!
  text: String!
  image: String
  video: String
  date: DateTime!
}
