scalar Date
scalar Node

type MarkdownRemark implements Node {
  frontmatter: Frontmatter
  fields: Fields
}
type Fields {
  slug: String
}
type Frontmatter {
  pages: Pages
  events: EventPage
  contact: Contact
  navigation: Navigation
  eventSettings: EventSettings
}
type Pages {
  landing: LandingPage
  team: TeamPage
  services: ServicesPage

  coaching: ServicesPage
  leading: ServicesPage
  learning: ServicesPage
}
type Contact {
  address: String
  email: String
  phone1: String
  phone2: String
  link: String
}
type Navigation {
  links: [NavigationLink!]!
}
type NavigationLink {
  label: String!
  url: String!
  description: String
}
type EventSettings {
  refundPolicy: String
}

type LandingPage {
  collection: String
  hero: Hero!
  about: About!
  services: [Service!]!
  products: [Product!]!
  testimonials: [Testimonial!]!
  title: String
  videos: [Video!]!
}

type Hero {
  title: String
  image: String
}

type About {
  text: String
  image: String
}

type Service {
  title: String
  image: String
  name: String
  description: String
}

type Product {
  description: String
  image: String
  title: String
  subtitle: String
  link: String
}

type Testimonial {
  author: String
  role: String
  testimonial: String
}
type Video {
  link: String
  title: String
  subtitle: String
}

type TeamPage {
  collection: String
  hero: Hero
  members: [Member]
}
type Member {
  name: String!
  role: String!
  photo: String!
  bio: String!
  linkedin: String
  video: String
}

type ServicesPage {
  collection: String
  hero: Hero
  explanation: Explanation
  benefits: String
}

type Explanation {
  text: String!
  image: String!
}

type EventPage {
  id: String!
  collection: String!
  slug: String!
  title: String!
  subtitle: String!
  description: String!
  image: String!
  video: String
  date: Date!
  duration: Int!
  language: [Language!]!
  isOnline: Boolean!
  location: String
  tickets: [Ticket!]!
}

enum Language {
  EN
  ES
}

type Ticket {
  id: String!
  description: String!
  price: Int!
  endsOn: String!
}
